#!/usr/bin/env python
# Python Example for Python GitHub Webhooks
# File: push-myrepo-master

import sys
import json

outfile = '/tmp/hook-pull_request.log'


with open(sys.argv[1], 'r') as jsf:
  payload = json.loads(jsf.read())

is_merged = False
  
try:
  ### Do something with the payload
  state = payload['pull_request']['state']
  if state == "closed" and payload['action'] == "closed":
    is_merged = payload['pull_request']['merged']
except:
  pass  

with open(outfile, 'w') as f:
  if is_merged:
    f.write("merged\n")
  else:
    f.write("not merged\n")
